image: node:alpine
variables:
  WEBPACK_MODE: production
  PATH_PREFIX: "/vigilo-ui"
pages:
  script:
    - npm install
    - npm run webpack
    - mv dist public
    - find .

  artifacts:
    paths:
      - public
  only:
    - master
