version: "3.0"
services:
  webpack:
    image: node:15
    environment:
      WEBPACK_MODE: ${WEBPACK_MODE:-production}
    volumes:
      - .:/app
    working_dir: /app
    command: "sh -c 'npm install && npm run webpack'"