version: "3.0"
services:
  webpack:
    image: node:15
    environment:
      WEBPACK_MODE: ${WEBPACK_MODE:-development}
    ports:
      - "${BIND}:80"
    volumes:
      - .:/app
    working_dir: /app
    command: "sh -c 'npm install && npm run server'"
